/* eslint-disable no-restricted-globals */
import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

const SUPABASE_URL = 'https://wbwxhmpjxwmsybpxycog.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indid3hobXBqeHdtc3licHh5Y29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwODkzMzAsImV4cCI6MjA4NjY2NTMzMH0.Cp2b6pU-fFrfwcVY08OQp4ng9tO3mCiX8U8VyCC37bg';

self.addEventListener('push', (event) => {
    console.log('[SW] Push Received:', event.data?.text());
    let data = {};
    try {
        data = event.data ? event.data.json() : {};
    } catch (e) {
        console.error('Error parsing push data:', e);
    }

    const title = data.title || 'Nouvelle Mission 📦';
    const options = {
        body: data.body || 'Une nouvelle mission a été assignée.',
        icon: '/pwa-192x192.png',
        badge: '/pwa-192x192.png',
        vibrate: [200, 100, 200],
        data: data.data || {},
        actions: [
            { action: 'accept', title: '✅ Accepter', icon: '/icons/check.png' },
            { action: 'decline', title: '❌ Refuser', icon: '/icons/cross.png' }
        ],
        tag: 'new-mission',
        renotify: true,
        requireInteraction: true
    };

    event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event) => {
    console.log('[SW] Notification click Received:', event.action);
    const action = event.action;
    const notificationData = event.notification.data || {};
    const { orderId, driverId } = notificationData;

    event.notification.close();

    if (action === 'accept' || action === 'decline') {
        event.waitUntil(
            handleOrderAction(orderId, action, driverId)
                .then(() => {
                    // Open or focus the app
                    return focusOrOpenApp(orderId);
                })
        );
    } else {
        // Normal click on notification
        event.waitUntil(focusOrOpenApp(orderId));
    }
});

async function focusOrOpenApp(orderId) {
    const urlToOpen = orderId ? `/missions/${orderId}` : '/missions';

    const clientList = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const client of clientList) {
        if (client.url === urlToOpen && 'focus' in client) {
            return client.focus();
        }
    }
    if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
    }
}

async function handleOrderAction(orderId, action, driverId) {
    if (!orderId || !action) return;

    const endpoint = `${SUPABASE_URL}/functions/v1/handle-mission-action`;

    try {
        const response = await fetch(endpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${SUPABASE_ANON_KEY}`
            },
            body: JSON.stringify({
                orderId,
                action,
                driverId
            })
        });

        if (!response.ok) {
            throw new Error(`Edge Function error: ${response.statusText}`);
        }

        console.log(`[SW] Successfully ${action}ed mission ${orderId}`);
    } catch (error) {
        console.error('[SW] Error handling mission action:', error);
    }
}
